<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DirectorioTelefonicoSeeder extends Seeder
{
    public function run(): void
    {
        if (! Schema::hasTable('directorio_grupo_cat') || ! Schema::hasTable('directorio_contacto_mst')) {
            return;
        }

        $tenantId = DB::table('tenants')->value('tenant_id') ?? 'Morell';

        $groups = [
            [
                'id' => 'DIRGR-COORD',
                'cod' => 'COORD',
                'nombre' => "Centres de coordinació i serveis de l'emergència",
                'orden' => 1,
            ],
            [
                'id' => 'DIRGR-MEDIOS',
                'cod' => 'MEDIOS',
                'nombre' => 'Mitjans de comunicació',
                'orden' => 2,
            ],
            [
                'id' => 'DIRGR-MUNI',
                'cod' => 'MUNI',
                'nombre' => 'Municipis veïns',
                'orden' => 3,
            ],
            [
                'id' => 'DIRGR-EV',
                'cod' => 'EV',
                'nombre' => 'Elements vulnerables',
                'orden' => 4,
            ],
            [
                'id' => 'DIRGR-ACOG',
                'cod' => 'ACOG',
                'nombre' => "Centres d'acollida",
                'orden' => 5,
            ],
        ];

        foreach ($groups as $group) {
            DB::table('directorio_grupo_cat')->updateOrInsert(
                ['dir_gr-id' => $group['id']],
                [
                    'dir_gr-tenant_id' => $tenantId,
                    'dir_gr-cod' => $group['cod'],
                    'dir_gr-nombre' => $group['nombre'],
                    'dir_gr-descrip' => null,
                    'dir_gr-activo' => 'SI',
                    'dir_gr-orden' => $group['orden'],
                ]
            );
        }

        $contacts = [
            [
                'id' => 'DIRCON-001',
                'grupo' => 'DIRGR-COORD',
                'cod' => null,
                'nombre' => 'CECAT TARRAGONA',
                'telefono' => '977297600',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 1,
            ],
            [
                'id' => 'DIRCON-002',
                'grupo' => 'DIRGR-COORD',
                'cod' => null,
                'nombre' => "Telèfon únic d'emergències",
                'telefono' => '112',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 2,
            ],
            [
                'id' => 'DIRCON-003',
                'grupo' => 'DIRGR-COORD',
                'cod' => null,
                'nombre' => 'CENTRE COORDINACIÓ SANITÀRIA TARRAGONA',
                'telefono' => '977252525',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 3,
            ],
            [
                'id' => 'DIRCON-004',
                'grupo' => 'DIRGR-COORD',
                'cod' => null,
                'nombre' => "CENTRE D'ATENCIÓ PRIMÀRIA",
                'telefono' => '977840656',
                'telefono_2' => '902111444',
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 4,
            ],
            [
                'id' => 'DIRCON-005',
                'grupo' => 'DIRGR-COORD',
                'cod' => null,
                'nombre' => "MOSSOS D'ESQUADRA",
                'telefono' => '112',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 5,
            ],
            [
                'id' => 'DIRCON-006',
                'grupo' => 'DIRGR-COORD',
                'cod' => null,
                'nombre' => 'MMEE - SERVEI CATALÀ DE TRÀNSIT',
                'telefono' => '933002296',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 6,
            ],
            [
                'id' => 'DIRCON-007',
                'grupo' => 'DIRGR-MEDIOS',
                'cod' => null,
                'nombre' => 'Catalunya Ràdio',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => '100.2 MHz FM',
                'responsable' => '934999333',
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 1,
            ],
            [
                'id' => 'DIRCON-008',
                'grupo' => 'DIRGR-MEDIOS',
                'cod' => null,
                'nombre' => 'RAC1',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => '87.7 MHz FM',
                'responsable' => '932704400',
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 2,
            ],
            [
                'id' => 'DIRCON-009',
                'grupo' => 'DIRGR-MEDIOS',
                'cod' => null,
                'nombre' => 'Ràdio Morell',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => '98.3 MHz FM',
                'responsable' => '977842744',
                'direccion' => null,
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 3,
            ],
            [
                'id' => 'DIRCON-010',
                'grupo' => 'DIRGR-MUNI',
                'cod' => null,
                'nombre' => 'La Pobla de Mafumet',
                'telefono' => '977840260',
                'telefono_2' => '977840260',
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => 'Sud',
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => 'Servei de Vigilància municipal',
                'orden' => 1,
            ],
            [
                'id' => 'DIRCON-011',
                'grupo' => 'DIRGR-MUNI',
                'cod' => null,
                'nombre' => 'Vallonga del Camp',
                'telefono' => '977840052',
                'telefono_2' => '670272256',
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => 'Nord-oest',
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 2,
            ],
            [
                'id' => 'DIRCON-012',
                'grupo' => 'DIRGR-MUNI',
                'cod' => null,
                'nombre' => 'El Rourell',
                'telefono' => '977840101',
                'telefono_2' => '659431932',
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => 'Nord',
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => 'Guàrdia municipal',
                'orden' => 3,
            ],
            [
                'id' => 'DIRCON-013',
                'grupo' => 'DIRGR-MUNI',
                'cod' => null,
                'nombre' => 'Els Garidells',
                'telefono' => '977625230',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => 'Nord-est',
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 4,
            ],
            [
                'id' => 'DIRCON-014',
                'grupo' => 'DIRGR-MUNI',
                'cod' => null,
                'nombre' => 'Perafort',
                'telefono' => '977625006',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => 'Est',
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => null,
                'orden' => 5,
            ],
            [
                'id' => 'DIRCON-015',
                'grupo' => 'DIRGR-MUNI',
                'cod' => null,
                'nombre' => 'Selva del Camp',
                'telefono' => '977844007',
                'telefono_2' => '656607227',
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => null,
                'situacion' => 'Oest',
                'coordenadas' => null,
                'capacidad' => null,
                'notas' => 'Guàrdia Municipal',
                'orden' => 6,
            ],
            [
                'id' => 'DIRCON-016',
                'grupo' => 'DIRGR-EV',
                'cod' => 'SP2',
                'nombre' => 'Guàrdia Municipal',
                'telefono' => '977948090',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Plaça de l'Església, 2",
                'situacion' => null,
                'coordenadas' => '349814.205,4561639.816',
                'capacidad' => null,
                'notas' => null,
                'orden' => 1,
            ],
            [
                'id' => 'DIRCON-017',
                'grupo' => 'DIRGR-EV',
                'cod' => 'A01',
                'nombre' => 'Ajuntament',
                'telefono' => '977840617',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Plaça Era del Castell, 5',
                'situacion' => null,
                'coordenadas' => '349767.759,4561627.108',
                'capacidad' => null,
                'notas' => null,
                'orden' => 2,
            ],
            [
                'id' => 'DIRCON-018',
                'grupo' => 'DIRGR-EV',
                'cod' => 'A02',
                'nombre' => 'Associació de voluntaris de',
                'telefono' => '977840726',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Plaça de l'Església, 1",
                'situacion' => null,
                'coordenadas' => '349811.273,4561636.534',
                'capacidad' => null,
                'notas' => null,
                'orden' => 3,
            ],
            [
                'id' => 'DIRCON-019',
                'grupo' => 'DIRGR-EV',
                'cod' => 'A03',
                'nombre' => 'Ajuntament Vell',
                'telefono' => '977840617',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Plaça de l'Església, 2",
                'situacion' => null,
                'coordenadas' => '349815.198,4561637.775',
                'capacidad' => null,
                'notas' => null,
                'orden' => 4,
            ],
            [
                'id' => 'DIRCON-020',
                'grupo' => 'DIRGR-EV',
                'cod' => 'BEN01',
                'nombre' => 'Petronor',
                'telefono' => '977840542',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Pau, 12',
                'situacion' => null,
                'coordenadas' => '349325.505,4561757.083',
                'capacidad' => null,
                'notas' => null,
                'orden' => 5,
            ],
            [
                'id' => 'DIRCON-021',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CAP01',
                'nombre' => "Centre d'Atenció Primària",
                'telefono' => '977840656',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda de Tarragona, s/n',
                'situacion' => null,
                'coordenadas' => '349712.979,4561375.764',
                'capacidad' => null,
                'notas' => null,
                'orden' => 6,
            ],
            [
                'id' => 'DIRCON-022',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CCSS01',
                'nombre' => 'Centre Obert',
                'telefono' => '977842639',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'C/La Coma, 2',
                'situacion' => null,
                'coordenadas' => '349765.50,4561503.45',
                'capacidad' => null,
                'notas' => null,
                'orden' => 7,
            ],
            [
                'id' => 'DIRCON-023',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CCSS02',
                'nombre' => 'Centre Cultural',
                'telefono' => '977842176',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'C/La Coma, 2',
                'situacion' => null,
                'coordenadas' => '349775.335,4561499.421',
                'capacidad' => null,
                'notas' => null,
                'orden' => 8,
            ],
            [
                'id' => 'DIRCON-024',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CCSS03',
                'nombre' => 'Centre de serveis per a la gent',
                'telefono' => '977841647',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Rambla de Pau Casals, 1',
                'situacion' => null,
                'coordenadas' => '349691.50,4561563.45',
                'capacidad' => null,
                'notas' => null,
                'orden' => 9,
            ],
            [
                'id' => 'DIRCON-025',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CCSS04',
                'nombre' => 'Emissora Municipal',
                'telefono' => '977842744',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'C/La Coma, 2',
                'situacion' => null,
                'coordenadas' => '349784.213,4561511.073',
                'capacidad' => null,
                'notas' => null,
                'orden' => 10,
            ],
            [
                'id' => 'DIRCON-026',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CCSS05',
                'nombre' => 'Teatre Auditori',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'C/La Coma, 2',
                'situacion' => null,
                'coordenadas' => '349764.846,4561508.010',
                'capacidad' => null,
                'notas' => null,
                'orden' => 11,
            ],
            [
                'id' => 'DIRCON-027',
                'grupo' => 'DIRGR-EV',
                'cod' => 'CEM01',
                'nombre' => 'Sala de Vetlles i Cementiri',
                'telefono' => '977840617',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Av. de la Granja S/N',
                'situacion' => null,
                'coordenadas' => '349831.738,4562072.048',
                'capacidad' => null,
                'notas' => null,
                'orden' => 12,
            ],
            [
                'id' => 'DIRCON-028',
                'grupo' => 'DIRGR-EV',
                'cod' => 'DEIX01',
                'nombre' => 'Deixalleria municipal',
                'telefono' => '637262731',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Av. de Valls, 11',
                'situacion' => null,
                'coordenadas' => '349811.903,4562169.637',
                'capacidad' => null,
                'notas' => null,
                'orden' => 13,
            ],
            [
                'id' => 'DIRCON-029',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ESC01',
                'nombre' => 'CEIP Ventura Gassol',
                'telefono' => '977842009',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Av. Camí de Reus, 13',
                'situacion' => null,
                'coordenadas' => '349443.680,4561538.480',
                'capacidad' => null,
                'notas' => null,
                'orden' => 14,
            ],
            [
                'id' => 'DIRCON-030',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ESC02',
                'nombre' => 'Escola de Música el Morell',
                'telefono' => '977842188',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Rambla Joan Maragall, 40',
                'situacion' => null,
                'coordenadas' => '349965.347,4561433.895',
                'capacidad' => null,
                'notas' => null,
                'orden' => 15,
            ],
            [
                'id' => 'DIRCON-031',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ESC03',
                'nombre' => 'IES el Morell',
                'telefono' => '977842057',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'C/César Martinell, 1',
                'situacion' => null,
                'coordenadas' => '349237.817,4561608.748',
                'capacidad' => null,
                'notas' => null,
                'orden' => 16,
            ],
            [
                'id' => 'DIRCON-032',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ESC04',
                'nombre' => "Llar d'infants",
                'telefono' => '977841510',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Plaça de l'Estatut, 2",
                'situacion' => null,
                'coordenadas' => '349520.087,4561453.946',
                'capacidad' => null,
                'notas' => null,
                'orden' => 17,
            ],
            [
                'id' => 'DIRCON-033',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ESG01',
                'nombre' => 'Parròquia de Sant Martí bisbe',
                'telefono' => '977843204',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Plaça de l'Església, 17",
                'situacion' => null,
                'coordenadas' => '349805.590,4561625.825',
                'capacidad' => null,
                'notas' => null,
                'orden' => 18,
            ],
            [
                'id' => 'DIRCON-034',
                'grupo' => 'DIRGR-EV',
                'cod' => 'HOT01',
                'nombre' => 'Hotel Morell',
                'telefono' => '622137317',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda de Tarragona, 23',
                'situacion' => null,
                'coordenadas' => '349612.637,4561552.573',
                'capacidad' => null,
                'notas' => null,
                'orden' => 19,
            ],
            [
                'id' => 'DIRCON-035',
                'grupo' => 'DIRGR-EV',
                'cod' => 'HOT02',
                'nombre' => 'Hotel Avenida',
                'telefono' => '622137317',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Tarragona, 7',
                'situacion' => null,
                'coordenadas' => '349677.096,4561336.572',
                'capacidad' => null,
                'notas' => null,
                'orden' => 20,
            ],
            [
                'id' => 'DIRCON-036',
                'grupo' => 'DIRGR-EV',
                'cod' => 'HOT04',
                'nombre' => 'Pensió Rosa',
                'telefono' => '977840332',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Carrer de Desprats, 30 baixos',
                'situacion' => null,
                'coordenadas' => '349832.962,4561447.853',
                'capacidad' => null,
                'notas' => null,
                'orden' => 21,
            ],
            [
                'id' => 'DIRCON-037',
                'grupo' => 'DIRGR-EV',
                'cod' => 'IES01',
                'nombre' => "Pavelló Municipal d'esports",
                'telefono' => '977842700',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda de Països Catalans, 6',
                'situacion' => null,
                'coordenadas' => '349305.554,4561387.043',
                'capacidad' => null,
                'notas' => null,
                'orden' => 22,
            ],
            [
                'id' => 'DIRCON-038',
                'grupo' => 'DIRGR-EV',
                'cod' => 'IES02',
                'nombre' => 'Zona esportiva municipal',
                'telefono' => '977842700',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Camí de Reus, 19',
                'situacion' => null,
                'coordenadas' => '349313.542,4561462.189',
                'capacidad' => null,
                'notas' => null,
                'orden' => 23,
            ],
            [
                'id' => 'DIRCON-039',
                'grupo' => 'DIRGR-EV',
                'cod' => 'IES03',
                'nombre' => 'Camp de Futbol municipal',
                'telefono' => '977842700',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Camí de Reus, 16',
                'situacion' => null,
                'coordenadas' => '349371.089,4561471.773',
                'capacidad' => null,
                'notas' => null,
                'orden' => 24,
            ],
            [
                'id' => 'DIRCON-040',
                'grupo' => 'DIRGR-EV',
                'cod' => 'IND1',
                'nombre' => 'Complex Industrial Repsol',
                'telefono' => '977758000',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'La Pobla de Mafumet, s/n',
                'situacion' => null,
                'coordenadas' => '350892.029,4561455.261',
                'capacidad' => null,
                'notas' => null,
                'orden' => 25,
            ],
            [
                'id' => 'DIRCON-041',
                'grupo' => 'DIRGR-EV',
                'cod' => 'IND2',
                'nombre' => 'Polígon Industrial del Morell',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'El Morell',
                'situacion' => null,
                'coordenadas' => '350991.738,4562243.439',
                'capacidad' => null,
                'notas' => null,
                'orden' => 26,
            ],
            [
                'id' => 'DIRCON-042',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ZE1',
                'nombre' => 'Parc Maria Mercè Marçal',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Carrer Montserrat Roig, 2',
                'situacion' => null,
                'coordenadas' => '349499.296,4561975.553',
                'capacidad' => null,
                'notas' => null,
                'orden' => 27,
            ],
            [
                'id' => 'DIRCON-043',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ZE2',
                'nombre' => "Parc Infantil de l'Estatut",
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Plaça de l'Estatut, 3857",
                'situacion' => null,
                'coordenadas' => '349566.216,4561463.858',
                'capacidad' => null,
                'notas' => null,
                'orden' => 28,
            ],
            [
                'id' => 'DIRCON-044',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ZE3',
                'nombre' => 'Plaça Francesc Macià',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Plaça Francesc Macià, s/n',
                'situacion' => null,
                'coordenadas' => '349486.745,4561597.900',
                'capacidad' => null,
                'notas' => null,
                'orden' => 29,
            ],
            [
                'id' => 'DIRCON-045',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ZE4',
                'nombre' => 'Plaça Era del Castell',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Plaça Era del Castell, s/n',
                'situacion' => null,
                'coordenadas' => '349753.915,4561599.402',
                'capacidad' => null,
                'notas' => null,
                'orden' => 30,
            ],
            [
                'id' => 'DIRCON-046',
                'grupo' => 'DIRGR-EV',
                'cod' => 'ZE5',
                'nombre' => 'Parc de la Coma',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => "Carrer Camí de l'Estació, s/n",
                'situacion' => null,
                'coordenadas' => '349769.660,4561347.652',
                'capacidad' => null,
                'notas' => null,
                'orden' => 31,
            ],
            [
                'id' => 'DIRCON-047',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M1',
                'nombre' => 'Granja dels Frares',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Carretera del Cementiri cap al riu',
                'situacion' => null,
                'coordenadas' => '351587.00,4563641.95',
                'capacidad' => null,
                'notas' => null,
                'orden' => 32,
            ],
            [
                'id' => 'DIRCON-048',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M2',
                'nombre' => 'Mas la Sínia',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Carretera del Cementiri, s/n',
                'situacion' => null,
                'coordenadas' => '350056.50,4562020.45',
                'capacidad' => null,
                'notas' => null,
                'orden' => 33,
            ],
            [
                'id' => 'DIRCON-049',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M3',
                'nombre' => 'Mas de Mercader',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Camí del carrer del mas la Sínia',
                'situacion' => null,
                'coordenadas' => '350104.50,4561933.95',
                'capacidad' => null,
                'notas' => null,
                'orden' => 34,
            ],
            [
                'id' => 'DIRCON-050',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M4',
                'nombre' => 'Mas de Marxant',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Camí de direcció contrària de la',
                'situacion' => null,
                'coordenadas' => '349454.00,4562534.95',
                'capacidad' => null,
                'notas' => null,
                'orden' => 35,
            ],
            [
                'id' => 'DIRCON-051',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M5',
                'nombre' => 'Mas de Mestre',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Ctra. de Reus / camí dels Majols',
                'situacion' => null,
                'coordenadas' => '348759.00,4561975.95',
                'capacidad' => null,
                'notas' => null,
                'orden' => 36,
            ],
            [
                'id' => 'DIRCON-052',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M6',
                'nombre' => 'Mas del Maset',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Camí Fondo, s/n',
                'situacion' => null,
                'coordenadas' => '350252.50,4561671.45',
                'capacidad' => null,
                'notas' => null,
                'orden' => 37,
            ],
            [
                'id' => 'DIRCON-053',
                'grupo' => 'DIRGR-EV',
                'cod' => 'M7',
                'nombre' => 'Molí de la Granja de Santes',
                'telefono' => null,
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Carretera del Cementiri cap al riu',
                'situacion' => null,
                'coordenadas' => '351722.00,4563649.95',
                'capacidad' => null,
                'notas' => null,
                'orden' => 38,
            ],
            [
                'id' => 'DIRCON-054',
                'grupo' => 'DIRGR-ACOG',
                'cod' => 'HOT01',
                'nombre' => 'Hotel Morell',
                'telefono' => '622137317',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Tarragona, 23',
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => 240,
                'notas' => null,
                'orden' => 1,
            ],
            [
                'id' => 'DIRCON-055',
                'grupo' => 'DIRGR-ACOG',
                'cod' => 'HOT02',
                'nombre' => 'Hotel Avenida',
                'telefono' => '622137317',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Tarragona, 7',
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => 132,
                'notas' => null,
                'orden' => 2,
            ],
            [
                'id' => 'DIRCON-056',
                'grupo' => 'DIRGR-ACOG',
                'cod' => 'HOT04',
                'nombre' => 'Pensió Rosa',
                'telefono' => '977840332',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Carrer de Desprats, 30',
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => 134,
                'notas' => null,
                'orden' => 3,
            ],
            [
                'id' => 'DIRCON-057',
                'grupo' => 'DIRGR-ACOG',
                'cod' => 'IES01',
                'nombre' => "Pavelló Municipal d'Esports",
                'telefono' => '977842700',
                'telefono_2' => null,
                'email' => null,
                'frecuencia' => null,
                'responsable' => null,
                'direccion' => 'Avinguda Països Catalans, 6',
                'situacion' => null,
                'coordenadas' => null,
                'capacidad' => 600,
                'notas' => null,
                'orden' => 4,
            ],
        ];

        foreach ($contacts as $contact) {
            DB::table('directorio_contacto_mst')->updateOrInsert(
                ['dir_con-id' => $contact['id']],
                [
                    'dir_con-tenant_id' => $tenantId,
                    'dir_con-dir_gr_id-fk' => $contact['grupo'],
                    'dir_con-cod' => $contact['cod'],
                    'dir_con-nombre' => $contact['nombre'],
                    'dir_con-telefono' => $contact['telefono'],
                    'dir_con-telefono_2' => $contact['telefono_2'],
                    'dir_con-email' => $contact['email'],
                    'dir_con-frecuencia' => $contact['frecuencia'],
                    'dir_con-responsable' => $contact['responsable'],
                    'dir_con-direccion' => $contact['direccion'],
                    'dir_con-situacion' => $contact['situacion'],
                    'dir_con-coordenadas' => $contact['coordenadas'],
                    'dir_con-capacidad' => $contact['capacidad'],
                    'dir_con-notas' => $contact['notas'],
                    'dir_con-activo' => 'SI',
                    'dir_con-orden' => $contact['orden'],
                ]
            );
        }
    }
}
